version: '3.8'
services:
  app:
    build: .
    image: hero-app
    container_name: hero-app
    environment:
      - NODE_ENV=docker
    ports:
      - 3000:3000
    depends_on:
      - redis
  redis:
    image: redis:7.2.5-alpine
    container_name: hero-cache
    ports:
      - 6379:6379
  vault:
    image: vault:1.13.3
    container_name: hero-vault
    volumes:
      - ./config:/vault/config
    ports:
      - 8200:8200
    cap_add:
      - IPC_LOCK
    environment:
      - VAULT_ADDR=http://localhost:8200
      - VAULT_TOKEN=myroot
    command: server -config=/vault/config